version: x.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Debug
install:
- cmd: git submodule update --init --recursive
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: appveyor-retry nuget restore
build:
  project: cr-patcher-csharp.sln
  parallel: true
  verbosity: normal
artifacts:
- path: cr-patcher-csharp/bin/Debug
  name: cr-patcher